package com.possible_triangle.content_packs.loader.definition.block;

import com.google.common.collect.BiMap;
import com.google.common.collect.ImmutableBiMap;
import com.mojang.serialization.Codec;
import com.mojang.serialization.DataResult;
import net.minecraft.world.level.block.SoundType;

public class SoundTypeCodec {

    private static final BiMap<String, SoundType> LOOKUP = new ImmutableBiMap.Builder<String, SoundType>()
            .put("empty", SoundType.EMPTY)
            .put("wood", SoundType.WOOD)
            .put("gravel", SoundType.GRAVEL)
            .put("grass", SoundType.GRASS)
            .put("lily_pad", SoundType.LILY_PAD)
            .put("stone", SoundType.STONE)
            .put("metal", SoundType.METAL)
            .put("glass", SoundType.GLASS)
            .put("wool", SoundType.WOOL)
            .put("sand", SoundType.SAND)
            .put("snow", SoundType.SNOW)
            .put("powder_snow", SoundType.POWDER_SNOW)
            .put("ladder", SoundType.LADDER)
            .put("anvil", SoundType.ANVIL)
            .put("slime_block", SoundType.SLIME_BLOCK)
            .put("honey_block", SoundType.HONEY_BLOCK)
            .put("wet_grass", SoundType.WET_GRASS)
            .put("coral_block", SoundType.CORAL_BLOCK)
            .put("bamboo", SoundType.BAMBOO)
            .put("bamboo_sapling", SoundType.BAMBOO_SAPLING)
            .put("scaffolding", SoundType.SCAFFOLDING)
            .put("sweet_berry_bush", SoundType.SWEET_BERRY_BUSH)
            .put("crop", SoundType.CROP)
            .put("hard_crop", SoundType.HARD_CROP)
            .put("vine", SoundType.VINE)
            .put("nether_wart", SoundType.NETHER_WART)
            .put("lantern", SoundType.LANTERN)
            .put("stem", SoundType.STEM)
            .put("nylium", SoundType.NYLIUM)
            .put("fungus", SoundType.FUNGUS)
            .put("roots", SoundType.ROOTS)
            .put("shroomlight", SoundType.SHROOMLIGHT)
            .put("weeping_vines", SoundType.WEEPING_VINES)
            .put("twisting_vines", SoundType.TWISTING_VINES)
            .put("soul_sand", SoundType.SOUL_SAND)
            .put("soul_soil", SoundType.SOUL_SOIL)
            .put("basalt", SoundType.BASALT)
            .put("wart_block", SoundType.WART_BLOCK)
            .put("netherrack", SoundType.NETHERRACK)
            .put("nether_bricks", SoundType.NETHER_BRICKS)
            .put("nether_sprouts", SoundType.NETHER_SPROUTS)
            .put("nether_ore", SoundType.NETHER_ORE)
            .put("bone_block", SoundType.BONE_BLOCK)
            .put("netherite_block", SoundType.NETHERITE_BLOCK)
            .put("ancient_debris", SoundType.ANCIENT_DEBRIS)
            .put("lodestone", SoundType.LODESTONE)
            .put("chain", SoundType.CHAIN)
            .put("nether_gold_ore", SoundType.NETHER_GOLD_ORE)
            .put("gilded_blackstone", SoundType.GILDED_BLACKSTONE)
            .put("candle", SoundType.CANDLE)
            .put("amethyst", SoundType.AMETHYST)
            .put("amethyst_cluster", SoundType.AMETHYST_CLUSTER)
            .put("small_amethyst_bud", SoundType.SMALL_AMETHYST_BUD)
            .put("medium_amethyst_bud", SoundType.MEDIUM_AMETHYST_BUD)
            .put("large_amethyst_bud", SoundType.LARGE_AMETHYST_BUD)
            .put("tuff", SoundType.TUFF)
            .put("calcite", SoundType.CALCITE)
            .put("dripstone_block", SoundType.DRIPSTONE_BLOCK)
            .put("pointed_dripstone", SoundType.POINTED_DRIPSTONE)
            .put("copper", SoundType.COPPER)
            .put("cave_vines", SoundType.CAVE_VINES)
            .put("spore_blossom", SoundType.SPORE_BLOSSOM)
            .put("azalea", SoundType.AZALEA)
            .put("flowering_azalea", SoundType.FLOWERING_AZALEA)
            .put("moss_carpet", SoundType.MOSS_CARPET)
            .put("pink_petals", SoundType.PINK_PETALS)
            .put("moss", SoundType.MOSS)
            .put("big_dripleaf", SoundType.BIG_DRIPLEAF)
            .put("small_dripleaf", SoundType.SMALL_DRIPLEAF)
            .put("rooted_dirt", SoundType.ROOTED_DIRT)
            .put("hanging_roots", SoundType.HANGING_ROOTS)
            .put("azalea_leaves", SoundType.AZALEA_LEAVES)
            .put("sculk_sensor", SoundType.SCULK_SENSOR)
            .put("sculk_catalyst", SoundType.SCULK_CATALYST)
            .put("sculk", SoundType.SCULK)
            .put("sculk_vein", SoundType.SCULK_VEIN)
            .put("sculk_shrieker", SoundType.SCULK_SHRIEKER)
            .put("glow_lichen", SoundType.GLOW_LICHEN)
            .put("deepslate", SoundType.DEEPSLATE)
            .put("deepslate_bricks", SoundType.DEEPSLATE_BRICKS)
            .put("deepslate_tiles", SoundType.DEEPSLATE_TILES)
            .put("polished_deepslate", SoundType.POLISHED_DEEPSLATE)
            .put("froglight", SoundType.FROGLIGHT)
            .put("frogspawn", SoundType.FROGSPAWN)
            .put("mangrove_roots", SoundType.MANGROVE_ROOTS)
            .put("muddy_mangrove_roots", SoundType.MUDDY_MANGROVE_ROOTS)
            .put("mud", SoundType.MUD)
            .put("mud_bricks", SoundType.MUD_BRICKS)
            .put("packed_mud", SoundType.PACKED_MUD)
            .put("hanging_sign", SoundType.HANGING_SIGN)
            .put("nether_wood_hanging_sign", SoundType.NETHER_WOOD_HANGING_SIGN)
            .put("bamboo_wood_hanging_sign", SoundType.BAMBOO_WOOD_HANGING_SIGN)
            .put("bamboo_wood", SoundType.BAMBOO_WOOD)
            .put("nether_wood", SoundType.NETHER_WOOD)
            .put("cherry_wood", SoundType.CHERRY_WOOD)
            .put("cherry_sapling", SoundType.CHERRY_SAPLING)
            .put("cherry_leaves", SoundType.CHERRY_LEAVES)
            .put("cherry_wood_hanging_sign", SoundType.CHERRY_WOOD_HANGING_SIGN)
            .put("chiseled_bookshelf", SoundType.CHISELED_BOOKSHELF)
            .put("suspicious_sand", SoundType.SUSPICIOUS_SAND)
            .put("suspicious_gravel", SoundType.SUSPICIOUS_GRAVEL)
            .put("decorated_pot", SoundType.DECORATED_POT)
            .put("decorated_pot_cracked", SoundType.DECORATED_POT_CRACKED)
            .build();

    public static final Codec<SoundType> CODEC = Codec.STRING.flatXmap(key -> {
        var soundType = LOOKUP.get(key);
        if(soundType  != null) return DataResult.success(soundType);
        return DataResult.error(() -> String.format("Unknown sound type with name %s".formatted(key)));
    }, soundType ->  {
        var key = LOOKUP.inverse().get(soundType);
        if(key  != null) return DataResult.success(key);
        return DataResult.error(() -> "custom sound types are not support yet");
    });

}
